### ISSUE TITLE
Checkpoint #1 ready for review

### ISSUE THREAD

**Issue by potatoesnmolasses** [potatoesnmolasses/NudgeWriting#1]
@pawaitemadisoncollege - added your account to collaborators but not able to tag yet.  Will let you know via Slack if the issue continues

**Comment by pawaitemadisoncollege** [comment]
Morning! I did get this notification - I'm guessing until I accepted the invitation that you sent, I'm not officially a member on your repo. I just accepted, so I'm guessing you'll be able to "see" me now.

**Comment by pawaitemadisoncollege** [comment]
Hi @potatoesnmolasses!

Thanks for sharing your indie project checkpoint 1! You are off to a very solid start (I see some code already) and have such a useful project idea to work on!

Following are my observations and suggestions:

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it. I appreciated the screenshot of the current site.

- [ ] I saw your note about a possible service for charts. Since charts are visual, the best thing to use here may be a [javascript library](https://www.wearedevelopers.com/magazine/top-javascript-charting-libraries). This doesn't count toward the requirement of consuming a service in java, but I think the result of using one of those will be better than some of the java based libraries. 
- [ ] I have not poked around too much for ai brainstorming or idea generator options, but some may have a cost associated, so I just wanted to say that there's no expectation that you pay for anything like that for your project. 

**User stories**

Your MVP user stories feel like they are right-sized for the semester while meeting the requirements of Ent Java - for example,  CRUD. That said, sometimes I am too optimistic/ambitious, so let's both keep an eye on how things progress and what, if anything needs to be delayed to V2. 

- [ ] Should probably have a sign out user story to be thorough. 

**Project plan**

Looks familiar! I hope that level of detail helps you understand what needs to be done and when.  

My biggest recommendation is to revisit the plan regularly, check off what's done, adjust as needed, and add new tasks as you think of them.


**Screen design**

I would normally add comments here about any user stories that are not fully represented in the screens, but you had that identified already - thanks! 

**Reflection statements/Time Log**

Great work consistently tracking!

**Other**

- [ ] I noticed some logs and property files which could contain information like usernames, passwords, etc. It would be a good idea to remove these from GitHub and add them to .gitignore. If you aren't able to find the details on how to do this, please post in slack as I'm sure other will run into this too
